<?php

namespace App\Exports;

use Maatwebsite\Excel\Classes\LaravelExcelWorksheet;
use Maatwebsite\Excel\Writers\LaravelExcelWriter;

class ReportExport
{
    protected $data;

    public function __construct(array $data)
    {
        $this->data = $data;
    }

    public function handleExport($excel)
    {
        $reportName = $this->data['report_name'] ?? 'Report';
        $fileName = strtolower(str_replace(' ', '_', $reportName)) . '_' . date('Y_m_d_H_i_s') . '.xlsx';

        $excel->create($fileName, function(LaravelExcelWriter $excel) {
            $excel->setTitle($this->data['report_name'] ?? 'Report');

            $excel->sheet('Report', function(LaravelExcelWorksheet $sheet) {
                // Add metadata
                $sheet->row(1, [$this->data['report_name'] ?? 'Report']);
                $sheet->row(2, ['Date Range:', $this->data['start_date'] . ' to ' . $this->data['end_date']]);
                $sheet->row(3, ['Generated By:', $this->data['generated_by']]);
                $sheet->row(4, ['Generated At:', $this->data['generated_at']]);
                $sheet->row(5, ['Total Records:', $this->data['record_count']]);

                // Add headers
                $headers = $this->getHeaders();
                $sheet->row(7, $headers);

                // Style headers
                $sheet->row(7, function($row) {
                    $row->setBackground('#4472C4');
                    $row->setFontColor('#FFFFFF');
                    $row->setFontWeight('bold');
                });

                // Add data rows
                $rowNumber = 8;
                if (!empty($this->data['data'])) {
                    foreach ($this->data['data'] as $rowData) {
                        $row = $this->formatRow($rowData);
                        $sheet->row($rowNumber, $row);
                        $rowNumber++;
                    }
                }

                // Auto-size columns
                foreach (range('A', $sheet->getHighestColumn()) as $column) {
                    $sheet->getColumnDimension($column)->setAutoSize(true);
                }
            });
        })->export('xlsx');
    }

    private function getHeaders()
    {
        // Same logic as before for headers
        $reportType = $this->data['report_type'] ?? 'generic';

        switch ($reportType) {
            case 'pharmacist_registrations':
                return ['ID', 'Full Name', 'Email', 'SLMC Reg No', 'Contact No', 'Status', 'Pharmacy Name', 'Pharmacy Address', 'Approved By', 'Registration Date'];

            // ... other cases ...
        }

        return ['Data'];
    }

    private function formatRow($rowData)
    {
        // Same logic as before for formatting rows
        $reportType = $this->data['report_type'] ?? 'generic';

        if (is_object($rowData)) {
            $rowData = (array) $rowData;
        }

        switch ($reportType) {
            case 'pharmacist_registrations':
                return [
                    $rowData['id'] ?? '',
                    $rowData['full_name'] ?? ($rowData['first_name'] . ' ' . $rowData['last_name'] ?? ''),
                    // ... other fields ...
                ];
            // ... other cases ...
        }

        return array_values($rowData);
    }
}
