<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report_name }}</title>
    <style>
        body { font-family: Arial; font-size: 10px; line-height: 1.2; }
        .header { text-align: center; margin-bottom: 15px; padding-bottom: 10px; border-bottom: 2px solid #333; }

        .header h1 { margin: 5px 0; color: #333; }

        .subtitle { color: #666; margin: 3px 0; }

        .info { margin-bottom: 15px; padding: 10px; background: #f5f5f5; border-radius: 5px; }

        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 9px; }

        th { background: #333; color: white; padding: 5px; border: 1px solid #ddd; }

        td { padding: 4px; border: 1px solid #ddd; }

        tr:nth-child(even) { background: #f9f9f9; }

        .no-data { text-align: center; padding: 20px; color: #666; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">

<h1>{{ $report_name }}</h1>
    <div class="subtitle">NMRA -  {{ date('F d, Y', strtotime($start_date)) }} to {{ date('F d, Y', strtotime($end_date)) }}</div>
    </div>

    <div class="info">
        <strong>Report Type -</strong> {{ ucwords(str_replace('_', ' ', $report_type)) }} -
        <strong>Generated By -</strong> {{ $generated_by }} -
        <strong>Generated At -</strong> {{ $generated_at }} -
        <strong>Total Records -</strong> {{ number_format($record_count) }}
    </div>

    @if($record_count > 0)
        <table>
        <thead>
            <tr>
                @foreach(array_keys((array)$data[0]) as $column)
                    <th>{{ ucwords(str_replace('_', ' ', $column)) }}</th>
                @endforeach
            </tr>
        </thead>
            <tbody>
                @foreach($data as $row)
                    <tr>
                        @foreach($row as $value)
                            <td>
                                @if(is_string($value) && (str_contains($value, '-') || str_contains($value, ':')))
                                    {{ !empty($value) && $value != 'N/A' ? date('Y-m-d', strtotime($value)) : 'N/A' }}
                                @else
                                    {{ $value ?? 'N/A' }}
                                @endif
                            </td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="no-data">No records found for the selected date range.</div>
    @endif

</body>
</html>
